* Overview

P2p2json is a very simple Inkscape extension to extract
data about a point-2-point map to JSON. Run the extension
in Inkscape without giving an output filename to get some
more information (or read the script in *p2p2json.py*).


* Install

Copy the py and inx files to where your Inkscape extensions
are (eg *~/.config/inkscape/extensions*).

* License

Copyright 2013 Pelle Nilsson

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

