* Overview

P2p2json is a very simple Inkscape extension to extract
data about a point-2-point map to JSON. Run the extension
in Inkscape without giving an output filename to get some
more information (or read the script in *p2p2json.py*).


* Running in Inksape

Copy the py and inx files to where your Inkscape extensions
are (eg *~/.config/inkscape/extensions*).

Run from the Extensions - Boardgames submenu.

* Running from command-line (advanced users)

You can run this as a stand-alone script without Inkscape (although
you will need to copy the inkex.py and simplepath.py files from the
Inkscape extensions directory first (advanced users can figure
that out)). Example of running on command-line:

 ./p2p2json.py -o /tmp/test1.json examples/test1.svg  > /dev/null

* License

Copyright 2013 Pelle Nilsson

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

